server:
  port: 7082
  address: 0.0.0.0

gemini:
  api:
    key: 3231211212121
spring:
  datasource:
    url: jdbc:postgresql://82.25.110.235:5432/bored
    username: boredapp
    password: xecsaV-5kojfu-dinnuj
    driver-class-name: org.postgresql.Driver
    hikari:
      keepalive-time: 300000   # 5 min ping to prevent idle disconnects
      validation-timeout: 5000 # safety timeout
      leak-detection-threshold: 60000 # optional, 60s for debugging
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true